apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatbot-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector: 
    matchLabels: 
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: gcr.io/gcp-node-chatbot/chatbot:latest
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc
  labels: 
    app: chatbot-svc
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chatbot-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gcp-node-chatbot-ip
spec:
  backend:
    serviceName: chatbot-svc
    servicePort: 80
