apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatbot-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector: 
    matchLabels: 
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: gcr.io/gcp-node-chatbot/chatbot:latest
          ports:
            - containerPort: 4000
