apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chatbot-deploy
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector: 
    matchLabels: 
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: dialogflow-key
      containers:
        - name: chatbot
          image: gcr.io/gcp-node-chatbot/chatbot:latest
          ports:
            - containerPort: 4000
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: DUMMY_VAR_FOR_REDEPLOYMENT
            value: a4
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc
  labels: 
    app: chatbot-svc
spec:
  type: NodePort
  selector:
    app: chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chatbot-ing
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gcp-node-chatbot-ip
    networking.gke.io/managed-certificates: gcp-node-chatbot-cert
spec:
  backend:
    serviceName: chatbot-svc
    servicePort: 80
